from . import academic
from . import student
from . import attendance
from . import exam
from . import finance
from . import whatsapp_service
from . import whatsapp_template
from . import whatsapp_log
from . import res_config_settings
